---
title: Justin Jay Wang
timezone: America/New_York
collections:
  blog_tags:
    title: Blog Tags
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: post
- scope:
    path: ''
    type: posts
  values:
    permalink: "/:year/:title/"
    layout: post
    tags: 
    show_title: 
    image: 
- scope:
    path: ''
    type: blog_tags
  values:
    permalink: "/tags/:title/"
    layout: archive
url: http://blog.justinjay.wang
description: 'Blog of Justin Jay Wang, a multidisciplinary designer at Oak Studios
  in Brooklyn.

'
permalink: pretty
exclude:
- Gruntfile.js
- Gemfile.lock
- package.json
- README*
- node_modules
- ".gitignore"
gems:
- jekyll-seo-tag
- jekyll-paginate
paginate: 12
paginate_path: "/page/:num/"
markdown: kramdown
highlighter: rouge
excerpt_separator: |2+



sass:
  sass_dir: assets/css/
  style: compressed
repository: justinjaywang/blog
google_analytics: UA-15132368-15
date_format: "%-d %b %Y"
